services:
  stretching-app:
    image: gayun5313/stretching:latest
    ports:
      - "3000:3000"
    env_file:
      - /home/agong/hermi-env/.env
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: stretching
      MYSQL_DATABASE: stretching
      MYSQL_USER: root
      MYSQL_PASSWORD: stretching
    ports:
      - "3307:3306"
    volumes:
      - ./db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  db_data:
    driver: local
