name: Build, Push and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: docker build . -t gayun5313/stretching:latest

      - name: Push Docker image
        run: docker push gayun5313/stretching:latest

      - name: Deploy to server
        env:
          DOCKER_IMAGE: gayun5313/stretching:latest
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key

          scp -i private_key 8822 -o StrictHostKeyChecking=no deploy.sh $SERVER_USER@$SERVER_HOST:/tmp/
          ssh -i private_key 8822 -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST 'bash /tmp/deploy.sh'

      - name: Clean up
        run: rm private_key
        
