name: Build, Push and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker build -t gayun5313/stretching:latest .
          docker push gayun5313/stretching:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SERVER_PRIVATE_KEY }}

      - name: Deploy to server using Docker Compose
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          echo "Starting deployment process..."
          
          # Ensure the target directory exists with root privileges
          ssh -o StrictHostKeyChecking=no -p 22 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
            echo ${SERVER_PASSWORD} | sudo -S mkdir -p /home/${SERVER_USER}/hermi-server &&
            echo ${SERVER_PASSWORD} | sudo -S mkdir -p /home/${SERVER_USER}/hermi-server/deploy &&
            echo ${SERVER_PASSWORD} | sudo -S chown ${SERVER_USER}:${SERVER_USER} /home/${SERVER_USER}/hermi-server &&
            echo ${SERVER_PASSWORD} | sudo -S chown ${SERVER_USER}:${SERVER_USER} /home/${SERVER_USER}/hermi-server/deploy"
          
          # Copy docker-compose.yml to the server
          scp -o StrictHostKeyChecking=no -P 22 ${GITHUB_WORKSPACE}/docker-compose.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/${SERVER_USER}/hermi-server/deploy/docker-compose.yml

          # Run Docker Compose on the server
          ssh -o StrictHostKeyChecking=no -p 22 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
            echo ${SERVER_PASSWORD} | sudo -S docker compose -f /home/${SERVER_USER}/hermi-server/deploy/docker-compose.yml pull &&
            echo ${SERVER_PASSWORD} | sudo -S docker compose -f /home/${SERVER_USER}/hermi-server/deploy/docker-compose.yml up -d"
